### ISSUE TITLE
Duplicated python snippets

### ISSUE THREAD

**Issue by voidus** [rafamadriz/friendly-snippets#102]
The following snippets are defined multiple times, with similar but not exactly the same definitions (at least `def` and `while`, I only looked at those)

```
$ rg -o '(?:prefix...)"([^"]+)' -r '$1' -I snippets/python | sort | uniq --count | grep 2
      2 class
      2 def
      2 for
      2 if
      2 ipdb
      2 pdb
      2 property
      2 pudb
      2 while
```

I'm not sure what the intention with `snippets/python/base` and `snippets/python/python` is, if you could explain that I can sort it out.

**Comment by rafamadriz** [comment]
Hey, thanks for this, that's a great idea to search for duplicate snippets, didn't thought about it. 

> I'm not sure what the intention with snippets/python/base and snippets/python/python is, if you could explain that I can sort it out.

Most of the snippets in this repo are forked from other VSCode plugins that have snippets for certain languages, in the case of python, they were forked from [cstrap/python-snippets](https://github.com/cstrap/python-snippets). So yeah I didn't made most of the snippets in here. The idea was to have a collection of snippets for as much languages as possible in one place. But just forking snippets from other repos came with price of a bunch of duplicate stuff and things that are really not necessary. 

I've thinking about doing a purge because I feel like there's just to much, but I don't want people to update one day and suddenly some of the snippets they like aren't there. 

If you think you can help with the python snippets I would appreciate it, thanks.
