### ISSUE TITLE
Use single quote `'` instead of `"`

### ISSUE THREAD

**Issue by kuntau** [rafamadriz/friendly-snippets#108]
This is mostly my OCD thing. I'm always using single quote `'` whenever possible. It annoy the hell out of me when I'm using snippets completion it use double quote `"`

I have to change back every single of them, every time and it's kind of defeat the purpose of having snippets completion.

I know we can run pettier or any other formatter, but it's nice if we have setting preference whether to use single or double quote.

Thank you for your work

**Comment by rafamadriz** [comment]
I don't know if it's possible to add an option to choose between single and double quotes. This is just a snippets collection with a bunch of json files. In my case I have autoformatting so I really don't mind single or double quotes since they get fixed by the formatter. 

I honestly not going to spend time trying to add such option, PR could be welcome but I don't think that's possible.
