### ISSUE TITLE
Fennel snippets completely broken

### ISSUE THREAD

**Issue by monkoose** [rafamadriz/friendly-snippets#152]
For some reason they slow down nvim-cmp (when you select the snippet in cmp popup window there can be some huge delay 100+ms).

And even without delay snippets are useless, they just paste irrelevant text without any jump labels.
So as example 
```
  "var": {
    "prefix": "var",
    "body": "var name value)",
    "description": "Create a variable with var"
  },
```

should be something like
```
  "var": {
    "prefix": "var",
    "body": "var ${1:name} ${2:value})$0",
    "description": "Create a variable with var"
  },
```

**EDIT:** ok, seems like delay happens on the `nvim-cmp` or `luasnip` side, because even global snippets in fennel files add delay to switching between suggestions in the popup window.

**Comment by bryant-the-coder** [comment]
@OkelleyDevelopment

**Comment by OkelleyDevelopment** [comment]
I don't notice any issues with load times however, I do agree that the snippets are a little off. I can come back to this after I finish working on a solution for issue #105 though. Anyone else can feel free to make a PR for us to review if they want to speed the process up.

**Comment by OkelleyDevelopment** [comment]
@monkoose  Hello :wave:  

Just opened a PR with some updates to the snippet formatting that you can check out if you wish. 

With regards to the load delays, that is (as you have guessed) not something that is likely caused by this project in particular. I know from my own set up, the order in which I had snippets load can affect how nicely it loads 

i.e. Check how you have `nvim-cmp` configured  for source order as that might resolve the delays :eyes:
