### ISSUE TITLE
Change LICENSE snippets prefixes to avoid mistyping them

### ISSUE THREAD

**Issue by RenjiSann** [rafamadriz/friendly-snippets#255]
I really like this plugin, but it's really a pain in the ass when I'm writing some markdown text.
Typing `isc` and instantly getting the full copypasta of the ISC license is very annoying, and I wish I didn't do it several times a day. It also regularly happens with the lorem ipsum snippet.

I think there can be several solutions to this:
- Change the license snippet prefixes to something we're less probable to type.
- Add a way to disable some snippets depending on the filetype.

Please feel free to provide additional solutions to this.

**Comment by thenbe** [comment]
As a quick workaround if you don't make use of the license snippets, you can run this to get rid of them. It removes any key composed of only capital letters and numbers (MIT, GPL2, etc)

> Requires `jq`. Change the path if you're not using `packer`.

```bash
cd ~/.local/share/nvim/site/pack/packer/opt/friendly-snippets/snippets \
&& cat global.json | jq -c '. | with_entries(select(.key | select(type == "string") | test("^[A-Z0-9]+$") | not))' > global.json.tmp \
&& mv global.json.tmp global.json
```

**Comment by wbthomason** [comment]
If I may suggest a slightly simpler version of @thenbe's workaround:
```bash
cd ~/.local/share/nvim/site/pack/packer/opt/friendly-snippets/snippets \
&& cat global.json | jq -c '. | with_entries(select(.value.description | test("[lL]icense") | not))' > global.json.tmp \
&& mv global.json.tmp global.json
```

Searches for "License" or "license" in the description field instead of just checking the key.

**Comment by OkelleyDevelopment** [comment]
Very cool to see these solutions! 

I've been trying to determine if it's worth splitting the licenses into their own file and then allowing users to extend to include them on specific file types. 

Any immediate push back or other ideas? :thinking:

**Comment by RenjiSann** [comment]
I would say yes, it's worth it

**Comment by OkelleyDevelopment** [comment]
My bad, thought I had opened the PR earlier this week (only happens when I press the button lol). 

I'd appreciate feedback on whether or not this PR seems like a good approach. Essentially all filetypes do not have license snippets, but users can extend to include them all.

```lua
require("luasnip").extend_filetype("markdown", { "license"}) -- includes all license snippets
```

Alternatively I was thinking perhaps break each snippet into it's own license file and then having a directory of "licenses" where users could still extend their snippets similar to: 

```lua
require("luasnip").extend_filetype("markdown", { "mit_license"}) -- would target a single type
``` 

A pro (and con) of my current PR is that all snippets are loaded for the file type. Whereas the alternative is more flexible but requires the user to extend a file type to have each license they would like, which could accumulate fairly quickly. 

Let me know what you think @RenjiSann @thenbe

**Comment by RenjiSann** [comment]
LGTM. It will be much more practical :)

Thank you !
