### ISSUE TITLE
Add a custom snippets function

### ISSUE THREAD

**Issue by ADkun** [rafamadriz/friendly-snippets#264]
I might want to add my custom snippets to specific programming languages to make them tailored to my needs.

Currently, I can only achieve this goal by manually modifying cpp.json or global.json.

**Comment by REmerald** [comment]
Umm, this is just a collection of snippets (a bunch of json text) and not a lua plugin. I think you need to look into your snippet engine instead.  
Did you wanted to do something like [this](https://github.com/L3MON4D3/LuaSnip#add-snippets)?

If I did't guess it, maybe you could try studying [package.json](https://github.com/rafamadriz/friendly-snippets/blob/main/package.json), but it would be significantly different experience than modifing `cpp.json` or `global.json` because it's all data, not the code.

**Comment by OkelleyDevelopment** [comment]
@ADkun def checkout the link the @REmerald shared. 

- https://github.com/L3MON4D3/LuaSnip#add-snippets

That will show you how to setup your own snippets for specific languages. I'll keep this issue open for probably the next week in case you'd like some more target guidance from users here. 

:sunglasses:

**Comment by ADkun** [comment]
Thank you for your help, I've understood what I should do now.

**Comment by heit0r** [comment]
For others that may stumble across this thread:

Don't forget to have a `package.json` in your custom snippets folder. Examples for the content can be found in [LuaSnip documentation](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#loaders)

**Comment by heit0r** [comment]
For others that may stumble across this issue:

Don't forget to have a package.json in your custom snippets folder. Examples for the content can be found in [LuaSnip documentation](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#loaders)

**Comment by heit0r** [comment]
For others that may stumble across this issue:

Don't forget to have a `package.json` in your custom snippets folder. Examples for the content can be found in [LuaSnip documentation](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#loaders)
