### ISSUE TITLE
Add documentation for all snippets

### ISSUE THREAD

**Issue by MarcusXavierr** [rafamadriz/friendly-snippets#369]
what if we use a script to parse the json files and create a documentation for the lacking snippets?

**Comment by surmish** [comment]
what does it mean for snippets to be lacking? There are always going to be commands and code blocks that aren't covered by snippets. Clogging up the completion menu for trivial code segments would be a disservice than a benefit, these snippets should not be viewed as a language reference or a user guide.

**Comment by OkelleyDevelopment** [comment]
I think it was meant for the wiki. However, we've not really put time towards the "snippets" provided since you can just read the files. 

Not to discredit the exercise of writing such a script, I feel we should focus on cleaning up the existing snippets before exploring that path if any effort is to be put forward. With that said, I will close this particular issue. Do feel free to re-open if you have any further concerns/comments. :slightly_smiling_face:
