### ISSUE TITLE
Angular snippets

### ISSUE THREAD

**Issue by diego-rapoport** [rafamadriz/friendly-snippets#479]
Hi, angular snippets are not being loaded. I don't know if there's some specific config with `lazy_load()` function to make it work or something else, but I have the defaults working with friendly-snippets and the regular languages. Is this because the snippets are inside the `frameworks` folder?

**Comment by JonathanRangelB** [comment]
Hi there 👋 (I'm still a noob with nvim)

I had the same issue, I just added this to my init.lua (i'm currently on lazyvim):
```lua
require("luasnip").filetype_extend("typescript", { "angular" })
require("luasnip").filetype_extend("html", { "angular" })
```
The only "problem" with that config is that all angular snippets are loaded into .ts and also .html even if the snippets dont belong to the file type, I tryed to make it work with something like { "angular/html"}  since there is specific config for each into the angular folder, but at least you could have them available.

**Comment by diego-rapoport** [comment]
Hi! Thanks for your response. It really solves the problem of not showing the snippets exactly like you said, with the problem of the filetype.
