### ISSUE TITLE
Extending snippets by default. Why not?

### ISSUE THREAD

**Issue by heit0r** [rafamadriz/friendly-snippets#528]
I'm using nvim to code in python and I needed docstring snippets. I noted that friendly-snippets didn't have docstrings by default. Or so I thought. In the wiki page I discovered that I just needed `require("luasnip").filetype_extend("python", { "pydoc" })`. It worked wonderfully well and now I have a lot of nice snippets for docstrings. I'm still exploring them.

But my question is, why not load them by default? I mean, all .json files (comprehension.json, debug.json, python.json, unittest.json) are loaded by default for Python except for pydoc.json. So why not load this one too if it's still useful like the others? Performance issues?

Thank you.

**Comment by OkelleyDevelopment** [comment]
Hi @heit0r, 

@rafamadriz had said some years back that one goal of this repo is to maintain a "close to vanilla" style workflow with snippets with some QOL enhancements being included but not to overload the end user. 

At least with the current tooling, to achieve this goal we favor snippet extension since _exclusion_ of snippets is a bit more challenging. 

Hopefully this gives some needed context! If you have any issues or concerns, feel free to re-open this issue. :slightly_smiling_face:

**Comment by heit0r** [comment]
Indeed. Better like this. Thank you for your reply anyways.
