### ISSUE TITLE
React function component is being expanded inproperly

### ISSUE THREAD

**Issue by iDuuck** [rafamadriz/friendly-snippets#62]
I just installed friendly-snippets together with LuaSnip, and I am experiencing the following issue: When using the `rfc` snippet for typescript, I am having a bad time because `export const` is written as `exportconst`.

Before (it even shows the right example):
![image](https://user-images.githubusercontent.com/325241/131820937-cb7fa840-60a7-40c1-99d0-445da7d2ae97.png)

After:
![image](https://user-images.githubusercontent.com/325241/131821095-c5282139-196a-45b6-abc2-c2191f637305.png)

Is this a bug with LuaSnip or with friendly snippets? It shows the right in the preview window...

**Comment by rafamadriz** [comment]
I don't think the problem is the snippet, as you can see here: 

https://github.com/rafamadriz/friendly-snippets/blob/b68c56ac58dd405ea88a13310b9db2aa581b9a94/snippets/javascript/react-ts.json#L32

`export` and `const` are separated by a space, and as you said, it shows right in the preview. Also, I just tested changing the snippet by literally using new lines instead of `\n` and that didn't make any difference.

**Comment by iDuuck** [comment]
OK, will open a new issue on Luasnip repository. Thanks though, @rafamadriz!
