### ISSUE TITLE
Duplicate snippets

### ISSUE THREAD

**Issue by ChrisTsou** [rafamadriz/friendly-snippets#98]
There are many duplicate snippets with typescript since it loads javascript snips and then typescript snips on package.json.

Also if i extend a filetype with luasnip it duplicates snippets further.

**Comment by rafamadriz** [comment]
Sorry for the inconvenience.

Would removing javascript snippets from typescript be a solution ?  I don't do anything in typescript but I know that javascript and typescript are pretty similar (if not the same?) and that's why snippets from javascript are also added to typescript. But I don't know, it may be worth it to completely decouple these two to avoid this kind of issues. What you think @ChrisTsou ?

**Comment by ChrisTsou** [comment]
I will have to check the files but from what i have seen typescript file has also javascript snippets so by extending you get for example 2 'while' snippets. there are 2 solutions as i see it, remove duplicate snippets from typescript and extend it with js or do not extend and duplicate the snippets in the file. Both need a little bit of work and checking.

**Comment by ChrisTsou** [comment]
I have also opened an issue in [luasnip](https://github.com/L3MON4D3/LuaSnip/issues/219) and i think i agree with what L3MON4D3 says. the snippets shouldn't extend and the engine should handle that and you only have one point of control then.

**Comment by rafamadriz** [comment]
Hey, typescript is no longer loading typescript snippets. Sorry for the delay.
